INSERT INTO engagement_rings (
  slug,
  name,
  title,
  description,
  base_price_usd,
  currency,
  shape,
  setting_style,
  band_type,
  setting_profile
)
VALUES
(
  'ring-melody',
  'Melody',
  'Melody - Radiant 4 Claw Solitaire with Hidden Halo and Cathedral Setting Engagement Ring',
  'Melody features a radiant-cut centre stone held in a refined four-claw setting, with a discreet hidden halo and cathedral foundation adding balance and elevation. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'radiant'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-merida',
  'Merida',
  'Merida - Elongated Cushion Claw Solitaire with Bypass Band and Clustered Round-Marquise Accent Stones Engagement Ring',
  'Merida pairs an elongated cushion-cut centre stone with a contemporary bypass setting. Curved lines are finished with round and marquise accent stones creating an open, sculptural silhouette. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'elongated_cushion'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'accents'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-mia',
  'Mia',
  'Mia - Pear Claw Trilogy with Pear Side Stones, Pave Band and Cathedral High Setting Engagement Ring',
  'With a striking pear cut centre stone, the Mia design features two neighbouring pear cut stones held in a stunning 5-claw cathedral setting atop a 2/3 pavé band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'pear'::enum_ring_shape,
  'trilogy'::enum_ring_setting_style,
  'pave'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-miller',
  'Miller',
  'Miller - Emerald 4 Claw Solitaire with Wrap Around Hidden Halo Engagement Ring',
  'The Miller engagement ring showcases a stunning emerald cut solitaire enclosed by a 4-claw setting and completed with a wrap-around hidden halo. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-molly',
  'Molly',
  'Molly - Round 6 Claw Solitaire with Clustered Round Shoulder Stones Engagement Ring',
  'Featuring a dazzling round cut centre stone, the centrepiece of the Molly design is neighboured by ten delicate accent stones in a low-set basket setting. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-morgan',
  'Morgan',
  'Morgan - Pear and Radiant Claw Toi et Moi Engagement Ring',
  'Morgan is a stunning duo of pear cut and radiant cut stones, held in a beautiful toi et moi setting. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'radiant'::enum_ring_shape,
  'toi_et_moi'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-myrtle',
  'Myrtle',
  'Myrtle - Elongated Hexagon 6 Claw Trilogy with Tapered Baguette Side Stones Engagement Ring',
  'Myrtle is a modern take on the trilogy design, featuring a daring elongated hexagon cut centre stone framed by two tapered baguette side stones. A blend of clean, geometric lines from the step cuts with timeless symmetry, it brings a fresh, contemporary edge to a classic silhouette. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'elongated_hexagon'::enum_ring_shape,
  'trilogy'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-naomi',
  'Naomi',
  'Naomi - Round 6 Claw Solitaire with Crown Gallery and Pave Band Engagement Ring',
  'Naomi is a spectacular round solitaire featuring six eagle-tipped claws set low into a 2/3 pavé band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'pave'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-nara',
  'Nara',
  'Nara - Emerald Claw Solitaire with Hidden Halo and Floating Cathedral Low Setting Engagement Ring',
  'Nara is a modern solitaire that balances beauty with practicality. A low-set emerald-cut centre stone is paired with an open bridge and hidden halo, creating a subtle floating effect and a low profile that pairs seamlessly with a flush-fit wedding band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'emerald'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'low_set'::enum_ring_setting_profile
),
(
  'ring-natalie',
  'Natalie',
  'Natalie - Princess 4 Claw Solitaire with Hidden Halo and Cathedral Setting Engagement Ring',
  'Natalie is a timeless 4-claw solitaire design with a princess cut centre stone held atop an elegant cathedral setting and hidden halo. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'princess'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-nienna',
  'Nienna',
  'Nienna - Pear 5 Claw Solitaire with Hidden Halo Engagement Ring',
  'Nienna is a stunning 5-claw pear solitaire engagement ring set low into a polished band and completed by a sparkling hidden halo. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'pear'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-nina',
  'Nina',
  'Nina - Emerald 4 Claw Trilogy with Graduating Baguette Shoulder Stones Engagement Ring',
  'Nina is a breathtaking emerald trilogy engagement ring that plays on the art-deco or antique aesthetic with three gorgeous emerald cut stones. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'emerald'::enum_ring_shape,
  'trilogy'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-noelle',
  'Noelle',
  'Noelle - Round 4 Claw Solitaire with Trellis Gallery and Cathedral Setting Engagement Ring',
  'The Noelle engagement ring features a beautiful 4-claw round solitaire atop a uniquely curved trellis cathedral setting. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-nola',
  'Nola',
  'Nola - Round 4 Claw Solitaire with Halo and Cathedral Setting Engagement Ring',
  'Nola is an exquisite 4-claw round halo design complete with sweeping with a cathedral setting. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-noor',
  'Noor',
  'Noor - Round and Pear Claw Toi et Moi with Wave Band Engagement Ring',
  'Sophisticated in its distinct design, the Noor engagement ring features a striking combination of a round and pear cut centre stone set within a uniquely curved band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'toi_et_moi'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-nora',
  'Nora',
  'Nora - Emerald Claw Solitaire with Spiral Gallery and Cathedral Low Setting Engagement Ring',
  'The beautiful Nora engagement ring showcases an elegant emerald cut centre stone atop a uniquely twisted 4-claw cathedral setting. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'emerald'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'low_set'::enum_ring_setting_profile
),
(
  'ring-octavia',
  'Octavia',
  'Octavia - Round 4 Claw Trilogy with Round Side Stones and Trellis Gallery Engagement Ring',
  'Octavia is a timeless trilogy design featuring round cut stones and a beautiful woven trellis setting. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'trilogy'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-olive',
  'Olive',
  'Olive - Statement Emerald Bezel Solitaire with East West Setting and Open Cathedral High Setting Engagement Ring',
  'Olive is a beautifully refined design featuring an east-west emerald cut centre stone on a cathedral bezel setting. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'emerald'::enum_ring_shape,
  'bezel'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-olivia',
  'Olivia',
  'Olivia - Oval 4 Claw Solitaire with Cathedral Setting and Open Trellis Gallery Engagement Ring',
  'The beautiful Olivia engagement ring is a classic 4-claw oval solitaire design with a sweeping trellis setting. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'oval'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-paige',
  'Paige',
  'Paige - Oval 4 Claw Solitaire with Hidden Halo and Pave Band Engagement Ring',
  'Paige is an exquisite oval solitaire engagement ring with four eagle-tipped claws, a sparkling hidden halo and 2/3 pavé band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'oval'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'pave'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-parker',
  'Parker',
  'Parker - Emerald 4 Claw Solitaire with Marquise and Round Accent Stones Engagement Ring',
  'Parker is a charming emerald solitaire design with four eagle-tipped claws and a unique band characterised by round and marquise cut accent stones. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'accents'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-penelope',
  'Penelope',
  'Penelope - Oval Claw Solitaire with Hidden Halo and Triple Pave Band Engagement Ring',
  'Penelope is a stunning oval solitaire engagement ring with four eagle-tipped claws, a sparkling hidden halo and 2/3 triple pavé band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'oval'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'pave'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-phoebe',
  'Phoebe',
  'Phoebe - Oval 4 Claw Solitaire with Halo Engagement Ring',
  'The Phoebe engagement ring features a striking oval cut centre stone framed by an exquisite halo and four eagle-tipped claws. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'oval'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-pia',
  'Pia',
  'Pia - Marquise 2 Claw Solitaire with Wave Band and East West Setting Engagement Ring',
  'Pia showcases a marquise cut centre stone resting within two v-claws and a uniquely curved band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'marquise'::enum_ring_shape,
  'east_west'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-polly',
  'Polly',
  'Polly - Pear 5 Claw Solitaire with Clustered Round Shoulder Stones Engagement Ring',
  'Polly features a basket-set pear-shaped centre stone, accented by a delicate cluster of brilliant round stones. The design balances soft detail with a clean, refined silhouette. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-poppy',
  'Poppy',
  'Poppy - Elongated Cushion Claw Solitaire with Petal Gallery and Accented Tiara Detail Engagement Ring',
  'Poppy centres an elongated cushion stone in a refined four-claw setting, framed by a sculpted petal gallery. A discreet tiara-style hidden halo sits beneath, adding quiet detail and soft, modern structure. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'elongated_cushion'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'accents'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-racquel',
  'Racquel',
  'Racquel - Radiant 4 Claw Solitaire with Hidden Halo, Pave Band and Cathedral Setting Engagement Ring',
  'Raquel features a radiant-cut centre stone elevated in a cathedral setting with a hidden halo beneath the gallery. A pavé-set band adds structured detail, forming a clean, contemporary design with refined proportions. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'radiant'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'pave'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-raleigh',
  'Raleigh',
  'Raleigh - Emerald 4 Claw Solitaire with Pear Accents and Round Shoulder Stones Engagement Ring',
  'Raleigh is a stunning emerald cut engagement ring with round &amp;amp; pear accent stones, complete with a low basket setting and slim tapered band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'accents'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-rachel',
  'Rachel',
  'Rachel - Statement Radiant Bezel Solitaire with Open Cathedral Setting Engagement Ring',
  'Featuring a gorgeous radiant cut stone framed within a bezel setting, Rachel is completed by a sweeping cathedral band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'radiant'::enum_ring_shape,
  'bezel'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-rita',
  'Rita',
  'Rita - Round Claw Solitaire with Crossover Petal Gallery Engagement Ring',
  'Rita is a sweet round solitaire engagement ring characterised by a beautiful 6-claw setting designed to resemble the delicate petals of a rose. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-river',
  'River',
  'River - Marquise 4 Claw Solitaire with East West Setting and Raised Basket Gallery Engagement Ring',
  'The River engagement ring is an elegant east-west design featuring a marquise cut centre stone placed horizontally on a polished band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'marquise'::enum_ring_shape,
  'east_west'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-rosalia',
  'Rosalia',
  'Rosalia - Pear Claw Trilogy with Pear Side Stones and Floating Cathedral High Setting Engagement Ring',
  'Rosalia is an exquisite 5-claw pear trilogy showcasing a beautiful pear cut centre stone and two pear cut side stones atop a sweeping cathedral setting. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'pear'::enum_ring_shape,
  'trilogy'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-rose',
  'Rose',
  'Rose - Fluted Cigar Ring',
  'The Rose wedding ring is a modern take on a croissant ring with a pillowy cigar band and stunning fluted design. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-rosie',
  'Rosie',
  'Rosie - Cushion 4 Claw Solitaire with Hidden Halo Engagement Ring',
  'Rosie is a timeless cushion solitaire design complete with four eagle-tipped claws and a sparkling hidden halo. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'cushion'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-rowena',
  'Rowena',
  'Rowena - Emerald 4 Claw Solitaire with Hidden Halo, Pave Band and Cathedral Setting Engagement Ring',
  'Rowena is a stunning 4-claw emerald solitaire featuring a sparkling hidden halo, sweeping cathedral arches and a 2/3 pavé band, creating an effortless combination of modern elegance. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'emerald'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'pave'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-sadie',
  'Sadie',
  'Sadie - Elongated Cushion Claw Solitaire with Pear Accents and Round Shoulder Stones Engagement Ring',
  'Sadie is a graceful 4-claw elongated cushion trilogy design featuring a beautiful elongated cushion cut centre stone encapsulated in a tulip motif basket. The elongated shape of the marquise is perfectly complimented by its shouldered pear and round cut side stones. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'elongated_cushion'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'accents'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-sage',
  'Sage',
  'Sage - Oval Bezel Solitaire Engagement Ring',
  'Sage is a stunning bezel-set oval solitaire paired with a minimal band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'oval'::enum_ring_shape,
  'bezel'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-salma',
  'Salma',
  'Salma - Marquise and Pear Claw Toi et Moi with Open Band Engagement Ring',
  'Salma''s distinct pear and marquise duo is elevated with a beautiful open band in this iconic toi et moi engagement ring. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'pear'::enum_ring_shape,
  'toi_et_moi'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-sasha',
  'Sasha',
  'Sasha - Oval 8 Double Claw Solitaire with Hidden Halo, Pave Band and Cathedral Setting Engagement Ring',
  'The Sasha engagement ring is a striking oval solitaire featuring four double-tipped claws, a hidden halo and 2/3 pavé cathedral band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'oval'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'pave'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-savannah',
  'Savannah',
  'Savannah - Oval 4 Claw Solitaire with Double Sunburst Halo and Cathedral Setting Engagement Ring',
  'Savannah is a spectacular engagement ring featuring an oval cut centre stone framed by a charming halo, intricately set with an array of round cut accent stones and complete with a sweeping cathedral setting. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'oval'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-scarlett',
  'Scarlett',
  'Scarlett - Oval 4 Claw Solitaire with Hidden Halo and Cathedral Setting Engagement Ring',
  'The elegant Scarlett engagement ring elevates the simple 4-claw oval solitaire design with a hidden halo and beautiful cathedral setting. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'oval'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-selena',
  'Selena',
  'Selena - Cushion 4 Claw Trilogy with Pear Side Stones and Open Trellis Gallery Engagement Ring',
  'Selena is a classic cushion trilogy adorned with two pear cut side stones and a beautiful woven trellis setting. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'cushion'::enum_ring_shape,
  'trilogy'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-sena',
  'Sena',
  'Sena - Marquise 4 Claw Solitaire with Bypass Band Engagement Ring',
  'Sena features a marquise centre stone framed by an open bypass band. Subtle outward curves follow and contrast the stone’s shape, giving the design a sense of movement and quiet structure. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'marquise'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-shai',
  'Shai',
  'Shai - Pear East West Claw Solitaire with Wave Band Engagement Ring',
  'Shai features a stunning 3-claw pear solitaire resting within a uniquely curved band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'pear'::enum_ring_shape,
  'east_west'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-sharon',
  'Sharon',
  'Sharon - Oval 4 Claw Solitaire with Round Shoulder Stones Engagement Ring',
  'Sharon is an elegant, vintage-style oval solitaire balanced with six accent stones set low in a basket setting. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'oval'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-shelly',
  'Shelly',
  'Shelly - Oval Claw Solitaire with Bead Set Pave Wave Band and East West Setting Engagement Ring',
  'Shelly is a contemporary design featuring an oval centre stone held in four claws. A sculptural wave band curves beneath, with bead pavé detailing tracing the upper half of the band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'oval'::enum_ring_shape,
  'east_west'::enum_ring_setting_style,
  'pave'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-sheridan',
  'Sheridan',
  'Sheridan - Oval 4 Claw Solitaire with Pear Accents and Round Shoulder Stones Engagement Ring',
  'Sheridan is an elegant 4-claw oval trilogy design featuring an oval cut centre stone shouldered by pear and round cut side stones. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'oval'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'accents'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-sherry',
  'Sherry',
  'Sherry - Marquise 4 Claw Solitaire Engagement Ring',
  'The Sherry engagement ring features a breathtaking marquise cut centre stone bordered by a combination of round claws and v-claws. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'marquise'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-sierra',
  'Sierra',
  'Sierra - Oval Bezel Solitaire with Hidden Halo and Cathedral Setting Engagement Ring',
  'Sierra is a modern interpretation of the bezel design, encapsulating an oval-cut centre stone within a deep setting. A hidden pavé detail sits within the bezel, supported by a cathedral foundation for balanced structure. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'oval'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-silvana',
  'Silvana',
  'Silvana - Emerald 4 Claw Trilogy with Emerald Side Stones and Low Setting Engagement Ring',
  'Silvana is a timeless trilogy of emerald cut stones placed low in a beautiful basket setting. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'emerald'::enum_ring_shape,
  'trilogy'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'low_set'::enum_ring_setting_profile
),
(
  'ring-siobhan',
  'Siobhan',
  'Siobhan - Round Claw Solitaire with Hidden Halo, Pave Collar and Pave Band Engagement Ring',
  'Siobhan is a beautiful 6-claw round solitaire with a sparkling hidden halo and collar placed atop a 2/3 pavé band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'pave'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-sophia',
  'Sophia',
  'Sophia - Princess 4 Claw Solitaire with Angled Setting and Clustered Round Shoulder Stones Engagement Ring',
  'The Sophia engagement ring is a beautiful princess solitaire design characterised by a distinct pattern of dainty round cut accent stones set low on a polished band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-soraya',
  'Soraya',
  'Soraya - Oval Offset East West Claw Solitaire with Flat Cigar Band  Engagement Ring',
  'Soraya is a statement engagement ring with a breathtaking east-west oval solitaire held by four round claws on a bold cigar band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'oval'::enum_ring_shape,
  'east_west'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-stephanie',
  'Stephanie',
  'Stephanie - Marquise 4 Claw Solitaire Engagement Ring',
  'The Stephanie engagement ring is a classic 6-claw solitaire design, featuring a striking marquise cut centre stone set low on a sleek band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'marquise'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-suki',
  'Suki',
  'Suki - Pear East West Claw Solitaire with Raised Basket Gallery Engagement Ring',
  'Suki features an east-west set pear-cut centre stone, positioned low within a scooped basket. The design sits flush with a classic band for a clean, seamless profile. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'pear'::enum_ring_shape,
  'east_west'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-svea',
  'Svea',
  'Svea - Pear and Princess Claw Toi et Moi Engagement Ring',
  'Svea is a breathtaking toi et moi engagement ring featuring pear and princess cut centre stones. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'pear'::enum_ring_shape,
  'toi_et_moi'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-tahlia',
  'Tahlia',
  'Tahlia - Emerald and Pear Claw Toi et Moi with Hidden Halo Engagement Ring',
  'Tahlia is a classic toi et moi engagement ring with a high-set duo of pear and emerald cut stones and matching hidden halos. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'emerald'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-tanya',
  'Tanya',
  'Tanya - Oval and Emerald Claw Toi et Moi Engagement Ring',
  'Tanya is a timeless toi et moi design featuring oval cut and emerald cut centre stones, each held by four eagle-tipped claws. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'oval'::enum_ring_shape,
  'toi_et_moi'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-taylor',
  'Taylor',
  'Taylor - Vintage Style Elongated Cushion Claw Solitaire with Bezel Frame and Star Set Accent Stones and Milgrain Engagement Ring',
  'Taylor pairs an elongated cushion-cut centre stone with a bezel frame and four claws. Star-set side stones accent the shoulders, while a tapered band with milgrain detailing defines a refined, vintage-inspired design. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'elongated_cushion'::enum_ring_shape,
  'bezel'::enum_ring_setting_style,
  'accents'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-tessa',
  'Tessa',
  'Tessa - Round 6 Claw Solitaire with Petal Gallery and Tapered Band Engagement Ring',
  'The beautiful Tessa engagement ring features a round cut centre stone held in a charming 6-claw tulip-style setting atop a slim tapered band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-thea',
  'Thea',
  'Thea - Radiant 4 Claw Solitaire with Hidden Halo and Pave Band Engagement Ring',
  'Thea is a sophisticated 4-claw radiant solitaire engagement ring with the added sparkle of a hidden halo and 2/3 pavé band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'radiant'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'pave'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-tilly',
  'Tilly',
  'Tilly - Elongated Cushion Claw Solitaire with Petal Gallery and Accent Leaf Detail Engagement Ring',
  'Tilly is a 4-claw elongated cushion that offers a twist on a classic solitaire with an accented petal gallery. Emphasising beauty in the smallest details, a secret hidden halo is encased within the petite petals, offering support for a subtle yet elegant form. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'elongated_cushion'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'accents'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-trinity',
  'Trinity',
  'Trinity - Oval 4 Claw Solitaire with Twisted Band Engagement Ring',
  'Trinity features a gently twisted band leading to an oval centre stone held in a four-claw setting. A subtle hidden halo sits beneath, adding refined structural detail to this considered solitaire. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'oval'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-valeria',
  'Valeria',
  'Valeria - Emerald Bezel Solitaire with Hidden Halo and Cathedral Setting Engagement Ring',
  'Valeria is a modern interpretation of the bezel design, encapsulating an emerald-cut centre stone within a deep setting. A hidden pavé detail sits within the bezel, supported by a cathedral foundation for balanced structure. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'emerald'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-violetta',
  'Violetta',
  'Violetta - Elongated Cushion Claw Solitaire with Hidden Halo and Twisted Alternating Pave Band Engagement Ring',
  'Violetta is an elegant twisted engagement ring, where sleek pavé and polished metal intertwine in a refined half-circle. A 4-claw elongated cushion centre stone is illuminated by a hidden halo beneath Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'elongated_cushion'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'pave'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-wanda',
  'Wanda',
  'Wanda - Elongated Hexagon 6 Claw Trilogy with Kite Side Stones Engagement Ring',
  'The Wanda engagement ring is a striking trilogy design featuring a 6-claw step-cut elongated hexagon, two kite side stones and sweeping cathedral arches. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'elongated_hexagon'::enum_ring_shape,
  'trilogy'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-wendy',
  'Wendy',
  'Wendy - Elongated Cushion 4 Claw Solitaire with Hidden Halo, Tapered Band and Cathedral Setting Engagement Ring',
  'The Wendy engagement ring is a beautiful 4-claw elongated cushion design characterised by a sparkling hidden halo and slim tapered cathedral band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'elongated_cushion'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-willow',
  'Willow',
  'Willow - Radiant 4 Claw Solitaire with Clustered Round Shoulder Stones Engagement Ring',
  'Willow features a radiant-cut centre stone set within a basket setting, accented by a subtle cluster of brilliant round stones. The design balances fine detail with a clean, considered silhouette. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-winnie',
  'Winnie',
  'Winnie - Elongated Cushion 4 Claw Solitaire with Clustered Round Shoulder Stones Engagement Ring',
  'The Winnie is a charming basket-set elongated cushion design with a glamorous array of round accent stones adorning the centrepiece. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'elongated_cushion'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-yasmine',
  'Yasmine',
  'Yasmine - Elongated Cushion 4 Claw Solitaire with Hidden Halo and Cathedral Setting Engagement Ring',
  'Yasmine is a timeless elongated cushion solitaire, featuring a sparkling hidden halo within an elegant four-claw setting. Its sweeping cathedral band adds a touch of sophistication, creating a versatile design that effortlessly blends classic elegance with modern style. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'elongated_cushion'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-zara',
  'Zara',
  'Zara - Radiant East West Claw Solitaire with Raised Basket Gallery Engagement Ring',
  'Fiona is an east–west set radiant cut centre stone positioned low within a scooped basket. The setting allows the profile to sit flush against a classic band, creating a clean, understated design with smooth, continuous lines. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'radiant'::enum_ring_shape,
  'east_west'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-zariyah',
  'Zariyah',
  'Zariyah - Marquise 6 Claw Solitaire with Hidden Halo Engagement Ring',
  'The beauty of the classic 6-claw marquise solitaire is elevated in the Zariyah ring with the added sparkle of a hidden halo. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'marquise'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-zelda',
  'Zelda',
  'Zelda - Oval Bezel Trilogy Engagement Ring',
  'The Zelda engagement ring is a beautiful trilogy of three bezel-set oval cut stones, creating a wonderfully symbiotic look. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'oval'::enum_ring_shape,
  'trilogy'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-zoe',
  'Zoe',
  'Zoe - Radiant Bezel Solitaire with Open Cathedral Setting Engagement Ring',
  'The Zoe engagement ring is a modern design showcasing a beautiful radiant cut centre stone framed within a bezel cathedral setting. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'radiant'::enum_ring_shape,
  'bezel'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-zya',
  'Zya',
  'Zya - Round Claw Solitaire with Trellis Gallery, Lattice Detail and Cathedral Low Setting Engagement Ring',
  'The Zya engagement ring features a beautiful round cut centre stone held in a graceful 6-claw woven trellis setting. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'low_set'::enum_ring_setting_profile
)
ON CONFLICT (slug) DO NOTHING;
