INSERT INTO engagement_rings (
  slug,
  name,
  title,
  description,
  base_price_usd,
  currency,
  shape,
  setting_style,
  band_type,
  setting_profile
)
VALUES
(
  'ring-adelyn',
  'Adelyn',
  'Adelyn - Round 4 Claw Trilogy with Pear Side Stones and Open Trellis Gallery Engagement Ring',
  'Adelyn is a timeless trilogy design featuring a beautiful round centre stone and two pear cut side stones seated within a trellis setting. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'trilogy'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-adina',
  'Adina',
  'Adina - Radiant 4 Claw Solitaire with Hidden Halo and Floating Cathedral Low Setting Engagement Ring',
  'Adina is a modern solitaire that doesn''t ask you to choose between beauty and practicality. Featuring a low-set radiant centre stone, its open bridge and hidden halo create a graceful floating effect, allowing the design to sit low on the finger while pairing seamlessly flush with a matching wedding band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'radiant'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'low_set'::enum_ring_setting_profile
),
(
  'ring-adrian',
  'Adrian',
  'Adrian - Statement Emerald East West Bezel Solitaire with Flat Cigar Band Engagement Ring',
  'Adrian is an east–west set emerald-cut centre stone enclosed within a statement bezel. The design flows into a flat-profile cigar band, creating clean lines and a modern, bold composition. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'emerald'::enum_ring_shape,
  'bezel'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-aida',
  'Aida',
  'Aida - Radiant 4 Claw Solitaire with Flat Cigar Band and Hidden Halo Engagement Ring',
  'Aida is a modern interpretation of the four-claw radiant-cut solitaire, set on a flat, straight-edged cigar band. A discreet hidden halo adds subtle brilliance, allowing the design’s width and presence to take focus. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'radiant'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-ainsley',
  'Ainsley',
  'Ainsley - Pear 5 Claw Solitaire with Wrap Around Hidden Halo Engagement Ring',
  'The Ainsley engagement ring is a high-set pear solitaire design with five eagle-tipped claws and a wrap-around hidden halo. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-aisha',
  'Aisha',
  'Aisha - Marquise 6 Claw Solitaire with Flat Cigar Band and Hidden Halo Engagement Ring',
  'Aisha is a modern take on the timeless 6-claw solitaire design featuring a breathtaking marquise cut centre stone, a sparkling hidden halo, and a flat, straight edged cigar band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'marquise'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-alessia',
  'Alessia',
  'Alessia - Round Bezel Solitaire with Clustered Round-Marquise Mixed Set Shoulder Stones Engagement Ring',
  'Alessia features a round bezel-set centre stone complemented by round and marquise accents along the shoulders. A bold central form is balanced by gentle sparkle, resulting in a considered, contemporary design with layered detail. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'bezel'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-alex',
  'Alex',
  'Alex - Round 4 Claw Solitaire with Hidden Halo and Triple Pave Band Engagement Ring',
  'Alex is a beautiful round solitaire engagement ring with a sophisticated of a triple pavé band and hidden halo. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'pave'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-alexandria',
  'Alexandria',
  'Alexandria - Round 6 Claw Solitaire with Pave Band Engagement Ring',
  'Alexandria is a signature 6-claw solitaire design featuring a round cut centre stone and 2/3 pavé band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'pave'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-alexia',
  'Alexia',
  'Alexia - Oval 4 Claw Trilogy with Pear Side Stones and Cathedral Setting Engagement Ring',
  'The Alexia trilogy ring features a striking oval centre stone and two pear cut side stones seated within a cathedral setting. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'oval'::enum_ring_shape,
  'trilogy'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-alia',
  'Alia',
  'Alia - Pear 5 Claw Solitaire Engagement Ring',
  'Minimal in design, the Alia engagement ring boasts a stunning pear cut centre stone framed by five eagle-tipped claws. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'pear'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-alice',
  'Alice',
  'Alice - Emerald 4 Claw Solitaire with Hidden Halo Engagement Ring',
  'The Alice engagement ring features a bold emerald solitaire and sparkling hidden halo seated atop a minimal band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'emerald'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-alina',
  'Alina',
  'Alina - Emerald 4 Claw Solitaire Engagement Ring',
  'Alina is a classic emerald solitaire engagement ring held within four eagle-tipped claws and seated atop a sleek band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'emerald'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-allison',
  'Allison',
  'Allison - Oval 6 Claw Solitaire with East West Setting Engagement Ring',
  'The Allison engagement ring adds a contemporary twist to a classic design with a beautiful east-to-west oval cut centre stone and 6-claw setting. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'oval'::enum_ring_shape,
  'east_west'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-alyssa',
  'Alyssa',
  'Alyssa - Oval 4 Claw Solitaire with Marquise and Round Accent Stones Engagement Ring',
  'The popular Alyssa design presents a stunning oval cut centre stone and a sleek band featuring two pairs of round and marquise cut side stones. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'oval'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'accents'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-amanda',
  'Amanda',
  'Amanda - Round 6 Claw Solitaire with Wrap Around Hidden Halo and Pave Band Engagement Ring',
  'Amanda''s elegant design boasts a 6-claw round solitaire, wrap-around hidden halo and 2/3 pavé band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'pave'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-amor',
  'Amor',
  'Amor - Pear and Emerald Claw Toi et Moi Engagement Ring',
  'The Amor toi et moi engagement ring presents the striking balance between a pear and emerald cut stone, emphasised by a sleek and minimal band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'emerald'::enum_ring_shape,
  'toi_et_moi'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-amy',
  'Amy',
  'Amy – 3 Claw Pear Solitaire',
  'Minimal and classic, Amy is a signature 3-claw pear solitaire engagement ring. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'pear'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-analyce',
  'Analyce',
  'Analyce - Emerald 4 Claw Solitaire with Halo and Pave Band Engagement Ring',
  'The Analyce engagement ring is a glamorous emerald halo design complete with a 2/3 pavé band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'emerald'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'pave'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-angelina',
  'Angelina',
  'Angelina - Radiant 4 Claw Solitaire with Cigar Band and Hidden Halo Engagement Ring',
  'The Angelina engagement ring adds a boldness to the traditional 4-claw radiant solitaire design with a striking cigar band and sparkling hidden halo. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'radiant'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-anna',
  'Anna',
  'Anna - Round 6 Claw Solitaire with Hidden Halo Engagement Ring',
  'Anna is a classic round solitaire design with the added feature of six eagle-tipped claws and a sparkling hidden halo. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-annika',
  'Annika',
  'Annika - Elongated Cushion 4 Claw Solitaire with Hidden Halo, Pave Band and Cathedral Setting Engagement Ring',
  'Annika is a stunning 4-claw elongated cushion solitaire engagement ring complete with a hidden halo, cathedral setting and 2/3 pavé band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'elongated_cushion'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'pave'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-annie',
  'Annie',
  'Annie - Princess 4 Claw Solitaire with Hidden Halo and Pave Band Engagement Ring',
  'The Annie engagement ring is a dazzling princess solitaire design complemented by four eagle-tipped claws, a hidden halo and 2/3 pavé band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'princess'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'pave'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-arabella',
  'Arabella',
  'Arabella - Oval 4 Claw Trilogy with Pear Side Stones and Pave Band Engagement Ring',
  'Arabella''s sweeping cathedral setting showcases an oval cut centre stone and two pear cut side stones atop a 2/3 pavé band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'oval'::enum_ring_shape,
  'trilogy'::enum_ring_setting_style,
  'pave'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-ari',
  'Ari',
  'Ari - Radiant 4 Claw Solitaire with Hidden Halo, Tapered Band and Cathedral Setting Engagement Ring',
  'Ari is an elegant radiant solitaire design with a beautiful cathedral setting and sparkling hidden halo. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'radiant'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-aria',
  'Aria',
  'Aria - Round 6 Claw Solitaire with Wrap Around Hidden Halo Engagement Ring',
  'The Aria engagement ring features an exquisite round cut centre stone enclosed in six eagle-tipped claws and completed with a wrap-around hidden halo. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-arielle',
  'Arielle',
  'Arielle - Oval 4 Claw Solitaire with Sunburst Halo and Cathedral Setting Engagement Ring',
  'Utterly unique in its design, Arielle is a beautiful oval halo engagement ring featuring round claws and a sweeping cathedral setting. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'oval'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-arlo',
  'Arlo',
  'Arlo - Oval 4 Claw Solitaire with Bezel Frame and East West Setting Engagement Ring',
  'Designed to be worn low set, the Arlo is an east west oval cut solitaire that blends vintage character with sculptural modern design for an effortlessly elevated silhouette that features a subtle under bezel frame and our signature eagle claws, offering the perfect balance for those torn between a bezel and a claw setting. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'oval'::enum_ring_shape,
  'bezel'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-ashlea',
  'Ashlea',
  'Ashlea - Round 4 Claw Solitaire with Hidden Halo, Pave Band and Cathedral Setting Engagement Ring',
  'Ashlea is an elegant round solitaire design accentuated by a sweeping cathedral setting, dazzling hidden halo and 2/3 pavé band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'pave'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-aspen',
  'Aspen',
  'Aspen - Pear 5 Claw Solitaire with Tapered Band and Cathedral Setting Engagement Ring',
  'The Aspen engagement ring highlights a striking pear cut centre stone with five eagle-tipped claws and slim tapered band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'pear'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-aster',
  'Aster',
  'Aster - Radiant Claw Solitaire with Petal Gallery and Accented Tiara Detail Engagement Ring',
  'Aster centres a radiant stone in a refined four-claw setting, framed by a sculpted petal gallery. A discreet tiara-style hidden halo sits beneath, adding quiet detail and soft, modern structure. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'radiant'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'accents'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-athena',
  'Athena',
  'Athena - Oval Claw Solitaire with Double Plain-and-Round-Accent Stones Band Engagement Ring',
  'Graceful yet bold, the Athena engagement ring features a beautiful oval cut centre stone, double band design and sparkling hidden halo. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'oval'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'accents'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-aubrey',
  'Aubrey',
  'Aubrey - Elongated Cushion 4 Double Claw Solitaire with Hidden Halo Engagement Ring',
  'The Aubrey engagement ring adds a unique touch to the classic elongated solitaire style with a double-tipped 4-claw setting and sparkling hidden halo. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'elongated_cushion'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-aurelie',
  'Aurelie',
  'Aurelie - Oval Claw Solitaire with Petal Gallery and Accent Leaf Detail Engagement Ring',
  'Aurelie is a 4-claw oval that offers a twist on a classic solitaire with an accented petal gallery. Emphasising beauty in the smallest details, a secret hidden halo is encased within the petite petals, offering support for a subtle yet elegant form. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'oval'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'accents'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-ava',
  'Ava',
  'Ava - Elongated Cushion 4 Claw Solitaire with Hidden Halo Engagement Ring',
  'Ava is a popular cushion solitaire design complete with a sparkling hidden halo, 4-claw setting and slim band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'elongated_cushion'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-avery',
  'Avery',
  'Avery - Oval 4 Double Claw Solitaire with Hidden Halo Engagement Ring',
  'The Avery engagement ring adds a unique touch to the classic oval solitaire design with four double-tipped claws, a basket setting and a hidden halo. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'oval'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-ayla',
  'Ayla',
  'Ayla - Classic Radiant Claw Trilogy Engagement Ring',
  'Ayla reimagines the classic trilogy with three matching radiant-cut stones, each held in refined eagle-claw settings. A cathedral foundation elevates each stone, bringing balance, symmetry, and structural clarity. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'radiant'::enum_ring_shape,
  'trilogy'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-bella',
  'Bella',
  'Bella - Oval 4 Claw Solitaire with Clustered Round Shoulder Stones Engagement Ring',
  'Vintage in style, Bella is a beautiful oval solitaire design framed by ten round cut side stones set low in a basket setting. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'oval'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-bethany',
  'Bethany',
  'Bethany - Oval 4 Claw Solitaire with Hidden Halo, Tapered Band and Cathedral High Setting Engagement Ring',
  'Bethany adds a distinct flair to the timeless oval solitaire design with a tapered band, cathedral-style setting and sparkling hidden halo. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'oval'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-bindi',
  'Bindi',
  'Bindi - Round 4 Claw Solitaire with Hidden Halo Engagement Ring',
  'Bindi is an exquisite round solitaire boasting four eagle-tipped claws and a dainty hidden halo. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-billie',
  'Billie',
  'Billie - Elongated Cushion Bezel Solitaire with Cathedral Setting Engagement Ring',
  'Billie is a stunning bezel-set elongated cushion solitaire set within a sweeping cathedral band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'elongated_cushion'::enum_ring_shape,
  'bezel'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-blair',
  'Blair',
  'Blair - Oval 4 Claw Solitaire with Split Shank and Cathedral Setting Engagement Ring',
  'The Blair engagement ring adds a distinct quality to the classic oval solitaire design with a uniquely divergent band seated within a cathedral 4-claw setting. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'oval'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-blossom',
  'Blossom',
  'Blossom - Pear Claw Solitaire with Petal Gallery and Accented Tiara Detail Engagement Ring',
  'Blossom centres a pear stone in a refined five-claw setting, framed by a sculpted petal gallery. A discreet tiara-style hidden halo sits beneath, adding quiet detail and soft, modern structure. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'pear'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'accents'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-bonnie',
  'Bonnie',
  'Bonnie - Round 4 Claw Solitaire with Hidden Halo and Cathedral Setting Engagement Ring',
  'Seated atop a spectacular cathedral setting, Bonnie is a beautiful round solitaire with four eagle-tipped claws and a sparkling hidden halo. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-brandi',
  'Brandi',
  'Brandi - Oval 4 Claw Solitaire with Marquise-Round Accent Stones and Hidden Halo Engagement Ring',
  'The striking Brandi design showcases a stunning 4-claw oval cut centre stone, sparkling hidden halo and a sleek band featuring two pairs of round and marquise cut side stones. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'oval'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'accents'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-bree',
  'Bree',
  'Bree - Elongated Cushion 4 Claw Trilogy with Pear Side Stones and Pave Band Engagement Ring',
  'Inspired by the Meghan trilogy, the Bree engagement ring features a breathtaking elongated cushion cut centre stone, two pear cut side stones and a sweeping cathedral setting atop a 2/3 pavè band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'elongated_cushion'::enum_ring_shape,
  'trilogy'::enum_ring_setting_style,
  'pave'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-briar',
  'Briar',
  'Briar - Round 6 Claw Solitaire with Trellis Gallery, Pave Band and Cathedral Setting Engagement Ring',
  'The Briar engagement ring is a unique take on the classic round solitaire design with a beautiful woven trellis setting, six eagle-tipped claws and a sparkling 2/3 pavè band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'pave'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-brooke',
  'Brooke',
  'Brooke - Pear 3 Claw Solitaire with Round Shoulder Stones Engagement Ring',
  'Brooke is a finely detailed pear solitaire design held within a 3-claw basket setting and framed each side by three round cut accent stones. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-brooklyn',
  'Brooklyn',
  'Brooklyn - Princess 4 Claw Solitaire with Wrap Around Hidden Halo and Pave Band Engagement Ring',
  'Brooklyn is a classic 4-claw princess solitaire boasting a wrap-around hidden halo and half pavé band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'pave'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-bronte',
  'Bronte',
  'Bronte - Oval 4 Claw Solitaire with Cigar Band and Hidden Halo Engagement Ring',
  'Bronte features a 4-claw oval solitaire, sparkling hidden halo and thick cigar band. This beautiful engagement ring is available in both high and low setting heights. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'oval'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-cali',
  'Cali',
  'Cali - Elongated Cushion 4 Claw Solitaire with Marquise-Round Accent Stones and Hidden Halo Engagement Ring',
  'Cali is a graceful elongated cushion solitaire design elevated by a sleek band featuring an alternating pattern of round and marquise cut side stones. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'elongated_cushion'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'accents'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-camilla',
  'Camilla',
  'Camilla - Elongated Cushion 4 Claw Solitaire with Hidden Halo and Pave Band Engagement Ring',
  'Starring an elegant elongated cushion centre stone, Camilla is a beautiful 4-claw design complete with a hidden halo and half pavé band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'elongated_cushion'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'pave'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-candice',
  'Candice',
  'Candice - Pear Claw Solitaire with Double Pave and Plain Band Engagement Ring',
  'Candice is a jaw-dropping double band pear solitaire complete with a 5-claw basket-set centre stone and half pavé band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'pear'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'pave'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-carly',
  'Carly',
  'Carly - Radiant 4 Claw Solitaire with Hidden Halo Engagement Ring',
  'Stunning in its simplicity, the Carly engagement ring is a classic radiant solitaire design featuring four eagle-tipped claws and a hidden halo. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'radiant'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-carmella',
  'Carmella',
  'Carmella - Emerald 4 Claw Solitaire with Flat Cigar Band and Hidden Halo Engagement Ring',
  'Carmella reimagines the classic four-claw emerald-cut solitaire with a flat, straight-edge cigar band. A discreet hidden halo adds light beneath the stone, while the band’s clean width gives the ring its quiet strength – whether worn alone or layered. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'emerald'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-caroline',
  'Caroline',
  'Caroline - Round 6 Claw Solitaire with Knife Edge Band Engagement Ring',
  'Arguably the most iconic solitaire design in history, the stunning Caroline engagement ring features a round cut centre stone, high-set 6-claw setting and knife-edge band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-cartia',
  'Cartia',
  'Cartia - Round Claw Solitaire with Round-Marquise Bezel Accent Stones Engagement Ring',
  'The Cartia design features a 4-claw round cut centre stone, balanced by a sleek band. Bezel-set round and marquise side stones bring subtle dimension and architectural detail to the design. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'bezel'::enum_ring_setting_style,
  'accents'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-casey',
  'Casey',
  'Casey - Oval East West Claw Solitaire with Bypass Band  Engagement Ring',
  'Casey centres an oval stone in a four-claw east–west setting, supported by a gently twisting bypass band. Soft curves wrap around the basket, creating a light, contemporary silhouette with sculptural balance. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'oval'::enum_ring_shape,
  'east_west'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-cataleya',
  'Cataleya',
  'Cataleya - Elongated Cushion 4 Claw Trilogy with Pear Side Stones and Cathedral Setting Engagement Ring',
  'Cataleya is a stunning elongated cushion trilogy with pear cut side stones and cathedral arches. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'elongated_cushion'::enum_ring_shape,
  'trilogy'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-cecilia',
  'Cecilia',
  'Cecilia - Oval 4 Claw Solitaire with Wrap Around Hidden Halo Engagement Ring',
  'The elegant Cecilia engagement ring is a 4-claw oval solitaire with a dazzling wrap-around halo. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'oval'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-chantelle',
  'Chantelle',
  'Chantelle - Marquise 6 Claw Trilogy with Pear Side Stones and Cathedral Setting Engagement Ring',
  'Chantelle centres a marquise stone with pear-cut accents on either side, brought together by a cathedral setting that creates a refined, harmonious three-stone silhouette. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'pear'::enum_ring_shape,
  'trilogy'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-charlie',
  'Charlie',
  'Charlie - Round 4 Claw Solitaire with Hidden Halo and Pave Band Engagement Ring',
  'Charlie is a sophisticated round solitaire featuring four round claws, 2/3 pavé band and a gorgeous hidden halo for extra sparkle. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'pave'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-charmaine',
  'Charmaine',
  'Charmaine - Elongated Cushion 4 Claw Trilogy with Round Side Stones and Lily Detail Engagement Ring',
  'The Charmaine elongated cushion trilogy design features two round cut side stones and an intricate petal design nestled within a cathedral setting. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'elongated_cushion'::enum_ring_shape,
  'trilogy'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-claudia',
  'Claudia',
  'Claudia - Cushion 4 Claw Solitaire with Hidden Halo and Pave Band Engagement Ring',
  'Claudia is a classic cushion soliatire engagement ring held within four eagle-tipped claws and complete with a hidden halo and 2/3 pavé band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'cushion'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'pave'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-cynthia',
  'Cynthia',
  'Cynthia - Classic Elongated Hexagon Claw Solitaire Engagement Ring',
  'The Cynthia is defined by an elongated hexagon-cut centre stone, held in place by six eagle-tipped claws and finished with a sleek, refined band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'elongated_hexagon'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-dahlia',
  'Dahlia',
  'Dahlia - Round Claw Solitaire with Petal Gallery and Accented Tiara Detail Engagement Ring',
  'Dahlia centres a round stone in a refined four-claw setting, framed by a sculpted petal gallery. A discreet tiara-style hidden halo sits beneath, adding quiet detail and soft, modern structure. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'accents'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-dakota',
  'Dakota',
  'Dakota - Radiant 4 Claw Solitaire with Cathedral Setting and Open Trellis Gallery Engagement Ring',
  'Dakota is an elegant radiant solitaire boasting a sweeping 4-claw trellis setting. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'radiant'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-daisy',
  'Daisy',
  'Daisy - Classic Oval 4 Claw Solitaire Engagement Ring',
  'Striking in its minimal design, the Daisy engagement ring features a stunning oval cut centre stone seated within four eagle-tipped claws. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'oval'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-daya',
  'Daya',
  'Daya - Elongated Cushion 4 Claw Solitaire with Bezel Frame and East West Setting Engagement Ring',
  'Designed to be worn low set, the Daya is an east west elongated cushion cut solitaire that blends vintage character with sculptural modern design for an effortlessly elevated silhouette that features a subtle under bezel frame and our signature eagle claws, offering the perfect balance for those torn between a bezel and a claw setting. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'elongated_cushion'::enum_ring_shape,
  'bezel'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-daphne',
  'Daphne',
  'Daphne - Oval Bezel Solitaire with Cathedral Setting Engagement Ring',
  'Daphne is a beautiful oval bezel design held within a sweeping cathedral setting. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'oval'::enum_ring_shape,
  'bezel'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-daniela',
  'Daniela',
  'Daniela - Round 6 Claw Solitaire with Solid Cathedral High Setting Engagement Ring',
  'Simple and sophisticated, the Daniela engagement ring features a round cut centre stone and six eagle-tipped claws. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-delilah',
  'Delilah',
  'Delilah - Round 6 Claw Solitaire with Trellis Gallery and Cathedral Setting Engagement Ring',
  'Delilah adds flair to the classic round solitaire design with six round claws and a woven trellis setting. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-delta',
  'Delta',
  'Delta - Elongated Hexagon 6 Claw Solitaire with Hidden Halo Engagement Ring',
  'The Delta engagement ring is a striking step-cut elongated hexagon solitaire cradled within six eagle-tipped claws and encircled by a sparkling hidden halo. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'elongated_hexagon'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-elena',
  'Elena',
  'Elena - Oval 4 Claw Trilogy with Pear Side Stones and Tulip Detail Engagement Ring',
  'The Elena trilogy is a charming three-stone design featuring an oval cut centre stone, two pear cut side stones and a beautiful petal setting. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'oval'::enum_ring_shape,
  'trilogy'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-eliana',
  'Eliana',
  'Eliana - Emerald 4 Claw Solitaire with Wrap Around Hidden Halo and Pave Band Engagement Ring',
  'Eliana makes a statement with a striking high-set 4-claw emerald cut centre stone, wrap-around hidden halo and 2/3 pavé band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'pave'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
)
ON CONFLICT (slug) DO NOTHING;
