INSERT INTO engagement_rings (
  slug,
  name,
  title,
  description,
  base_price_usd,
  currency,
  shape,
  setting_style,
  band_type,
  setting_profile
)
VALUES
(
  'ring-elise',
  'Elise',
  'Elise - Oval 4 Claw Solitaire with 6 Spaced Round Accent Stones and Hidden Halo Engagement Ring',
  'With an eye-catching oval cut centre stone, the Elise engagement ring is characterised by a sparkling hidden halo and a unique band set with round cut stones. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'oval'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'accents'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-ella',
  'Ella',
  'Ella - Round 4 Claw Trilogy with Round Side Stones and Pave Band Engagement Ring',
  'Ella is a classic round trilogy design accentuated by round claws, sweeping trellis setting and half pavé band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'trilogy'::enum_ring_setting_style,
  'pave'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-elle',
  'Elle',
  'Elle - Elongated Cushion Claw Solitaire with Hidden Halo, Opposing Marquise Accents and Cathedral High Setting Engagement Ring',
  'The Elle engagement ring showcases a 4-claw elongated cushion centre stone, illuminated by a hidden halo beneath. A refined cathedral setting gives height and presence, while opposing marquise-cut side stones taper delicately along the band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'elongated_cushion'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'accents'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-ellie',
  'Ellie',
  'Ellie - Radiant 4 Claw Solitaire with Wrap Around Hidden Halo and Pave Band Engagement Ring',
  'With a stunning radiant cut centre stone, the Ellie engagement ring is elevated by a wrap-around hidden halo and 2/3 pavé band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'pave'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-elphie',
  'Elphie',
  'Elphie - Emerald Claw Trilogy with Kite Side Stones Engagement Ring',
  'Elphie is a refined trilogy engagement ring, defined by a 4-claw step-cut emerald. Kite side stones taper alongside the centre, set within sweeping cathedral arches. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'emerald'::enum_ring_shape,
  'trilogy'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-elsie',
  'Elsie',
  'Elsie - Marquise 6 Claw Solitaire with Hidden Halo, Opposing Marquise Accents and Cathedral Setting Engagement Ring',
  'The Elsie engagement ring showcases a stunning 6-claw marquise cut centre stone, sparkling hidden halo and an elegant cathedral setting featuring two pairs of opposing marquise cut side stones delicately graduating along the band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'marquise'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'accents'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-ember',
  'Ember',
  'Ember Engagement Ring',
  'The Ember is a beautiful engagement ring from Cullen Jewellery.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-emily',
  'Emily',
  'Emily - Oval 4 Claw Solitaire with Tapered Band and Cathedral Setting Engagement Ring',
  'Emily is a beautiful oval solitaire design with four round claws, a slim tapered band and a stunning oval cut centre stone set low into a sleek band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'oval'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-emma',
  'Emma',
  'Emma - Classic Oval 4 Claw Solitaire with Hidden Halo Engagement Ring',
  'Popular for its timeless beauty, the Emma engagement ring is a classic 4-claw oval solitaire design complete with a sparkling hidden halo. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'oval'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-emmy',
  'Emmy',
  'Emmy - Asscher 4 Claw Solitaire Engagement Ring',
  'The exquisite Emmy engagement ring features an asscher cut centre stone held by four eagle-tipped claws and set low into a sleek band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'asscher'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-evangeline',
  'Evangeline',
  'Evangeline - Oval 4 Claw Solitaire with Wrap Around Hidden Halo and Pave Band Engagement Ring',
  'Evangeline features a round solitaire held in a refined six-claw setting, complemented by a wrap-around hidden halo and a pavé band extending two-thirds of the way around. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'oval'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'pave'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-eve',
  'Eve',
  'Eve - Marquise Claw Solitaire with Petal Gallery Engagement Ring',
  'The beautiful Eve engagement ring features a striking marquise cut centre stone held by six eagle-tipped claws within a beautiful petal-like setting. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'marquise'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-evelyn',
  'Evelyn',
  'Evelyn - Emerald 4 Claw Solitaire with East West Setting and Raised Basket Gallery Engagement Ring',
  'A signature east-west design, Evelyn modernises the timeless look of a solitaire ring by introducing directional appeal with a beautiful emerald cut stone set east-to-west on a polished band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'emerald'::enum_ring_shape,
  'east_west'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-everleigh',
  'Everleigh',
  'Everleigh - Elongated Cushion Bezel Solitaire with Hidden Halo and Cathedral Setting Engagement Ring',
  'Everleigh is a modern interpretation of the bezel design, encapsulating an elongated cushion-cut centre stone within a deep setting. A hidden pavé detail sits within the bezel, supported by a cathedral foundation for balanced structure. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'elongated_cushion'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-fiona',
  'Fiona',
  'Fiona - Elongated Cushion East West Claw Solitaire with Raised Basket Gallery Engagement Ring',
  'Fiona is an east–west set elongated cushion-cut centre stone positioned low within a scooped basket. The setting allows the profile to sit flush against a classic band, creating a clean, understated design with smooth, continuous lines. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'elongated_cushion'::enum_ring_shape,
  'east_west'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-francesca',
  'Francesca',
  'Francesca - Pear and Pear Claw Toi et Moi Engagement Ring',
  'Francesca is a beautiful toi et moi engagement ring featuring two pear cut centre stones positioned in a complementary manner to radiate a fresh yet timeless aesthetic. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'pear'::enum_ring_shape,
  'toi_et_moi'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-frankie',
  'Frankie',
  'Frankie - Statement Radiant East West Bezel Solitaire with Flat Cigar Band Engagement Ring',
  'Frankie is an east–west set radiant-cut centre stone enclosed within a statement bezel. The design flows into a flat-profile cigar band, creating clean lines and a modern, bold composition. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'radiant'::enum_ring_shape,
  'bezel'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-freya',
  'Freya',
  'Freya - Emerald 4 Claw Solitaire with Tapered Band and Cathedral Setting Engagement Ring',
  'Sleek in its design, the Freya engagement ring features an elegant emerald cut centre stone held by four round claws and set low on a slim tapered band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'emerald'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-freesia',
  'Freesia',
  'Freesia - Emerald Claw Solitaire with Petal Gallery and Accented Tiara Detail Engagement Ring',
  'Freesia centres a emerald stone in a refined four-claw setting, framed by a sculpted petal gallery. A discreet tiara-style hidden halo sits beneath, adding quiet detail and soft, modern structure. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'emerald'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'accents'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-gabrielle',
  'Gabrielle',
  'Gabrielle - Round 6 Claw Solitaire with Square Tips and Solid Cathedral Setting Engagement Ring',
  'The Gabrielle is a signature round solitaire design featuring a beautiful round cut centre stone and 6-claw setting, placed low on a polished band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-gemma',
  'Gemma',
  'Gemma - Oval Bezel Solitaire with Twisted Gallery Engagement Ring',
  'The Gemma engagement ring adds a distinct flourish to the classic oval solitaire with a bezel-set oval cut centre stone and unique, intertwining cathedral design. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'oval'::enum_ring_shape,
  'bezel'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-genevieve',
  'Genevieve',
  'Genevieve - Marquise 4 Claw Solitaire Engagement Ring',
  'Genevieve is a beautiful solitaire engagement ring showcasing a striking marquise cut centre stone held by four eagle-tipped claws. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'marquise'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-georgia',
  'Georgia',
  'Georgia - Round 4 Claw Solitaire with Flat Band and Cathedral Setting Engagement Ring',
  'Timeless in design, Georgia is a round solitaire engagement ring with four round claws and a beautiful cathedral setting. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-gigi',
  'Gigi',
  'Gigi - Marquise 6 Claw Solitaire with Cigar Band and Hidden Halo Engagement Ring',
  'Gigi is a sophisticated 6-claw marquise solitaire defined by its thick cigar band, which offers a bold yet timelessly classic look. Complete with a sparkling hidden halo, this graceful engagement ring is available in both high and low setting heights. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'marquise'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-ginny',
  'Ginny',
  'Ginny - Radiant 8 Claw Trilogy with Pear Side Stones and Pave Band Engagement Ring',
  'Ginny is an exquisite trilogy engagement ring showcasing a radiant cut centre stone and two pear side stones atop a cathedral 2/3 pavè band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'radiant'::enum_ring_shape,
  'trilogy'::enum_ring_setting_style,
  'pave'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-giselle',
  'Giselle',
  'Giselle - Marquise 4 Claw Solitaire with V Band Engagement Ring',
  'With four eagle-tipped claws and a sharp V point, Giselle is a sleek design featuring an exquisite marquise cut centre stone. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'marquise'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-glinda',
  'Glinda',
  'Glinda - Princess 4 Claw Solitaire Engagement Ring',
  'Glinda is a striking solitaire engagement ring with an elegant princess cut centre stone, thick basket setting and four sleek square claws. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'princess'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-grace',
  'Grace',
  'Grace - Oval 4 Claw Trilogy with Round Side Stones, Open Trellis Gallery and Tapered Band Engagement Ring',
  'Grace is a timeless trilogy design featuring a stunning oval cut centre stone and two round cut side stones placed within a trellis setting and tapered band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'oval'::enum_ring_shape,
  'trilogy'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-greta',
  'Greta',
  'Greta - Round 4 Claw Solitaire with Round Shoulder Stones Engagement Ring',
  'Sweet and feminine, Greta is a classic round solitaire design accentuated by round cut accent stones and seated in a gorgeous trilogy basket setting atop a tapered band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-gwyneth',
  'Gwyneth',
  'Gwyneth - Emerald 4 Claw Solitaire with Hidden Halo and Pave Band Engagement Ring',
  'With a stunning emerald cut centre stone held by a 4-claw setting, Gwyneth is completed by a sparkling hidden halo &amp;amp; 2/3 pavé band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'emerald'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'pave'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-halle',
  'Halle',
  'Halle - Round Claw Trilogy with Pear Side Stones and Knife Edge Band Engagement Ring',
  'Halle is an elegant trilogy ring with a round cut centre stone and pear cut side stones, finished within a graceful basket setting. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'trilogy'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-hannah',
  'Hannah',
  'Hannah - Marquise Claw Trilogy with Pear Side Stones and Hidden Halo Engagement Ring',
  'The Hannah engagement ring is a unique marquise trilogy ring, complete with two pear cut side stones and a hidden halo held within a cathedral setting on a slim tapered band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'pear'::enum_ring_shape,
  'trilogy'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-hayley',
  'Hayley',
  'Hayley - Oval 4 Claw Solitaire with Wave Band and East West Setting Engagement Ring',
  'Hayley features a beautiful 4-claw oval cut stone resting within a uniquely curved band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'oval'::enum_ring_shape,
  'east_west'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-hilary',
  'Hilary',
  'Hilary - Oval 4 Claw Solitaire with Cathedral High Setting Engagement Ring',
  'Hilary is a stunning oval solitaire engagement ring featuring a classic 4-claw setting complete with sweeping cathedral arches. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'oval'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-iris',
  'Iris',
  'Iris - Round 6 Claw Solitaire with Petal Gallery Engagement Ring',
  'Clasped by six eagle-tipped claws, the Iris engagement ring displays a stunning round cut stone set high within a uniquely feminine petal setting. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-isla',
  'Isla',
  'Isla - Oval 4 Claw Trilogy Engagement Ring',
  'Isla reimagines the classic trilogy with three matching oval stones in refined eagle-claw settings. A cathedral foundation lifts each stone, creating a balanced three-stone silhouette with quiet contemporary structure. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'oval'::enum_ring_shape,
  'trilogy'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-ivy',
  'Ivy',
  'Ivy - Oval 4 Claw Solitaire with Petal Gallery and Accented Tiara Detail Engagement Ring',
  'Ivy centres an oval stone in a refined four-claw setting, framed by a sculpted petal gallery. A discreet tiara-style hidden halo sits beneath, adding quiet detail and soft, modern structure. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'oval'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'accents'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-jacinta',
  'Jacinta',
  'Jacinta - Pear 5 Claw Solitaire with Marquise and Round Accent Stones Engagement Ring',
  'Jacinta is a beautiful 5-claw pear solitaire design accentuated by a sparkling band of alternating marquise and round cut accent stones. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'accents'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-jackie',
  'Jackie',
  'Jackie - Pear East West Claw Solitaire with Bypass Band  Engagement Ring',
  'Jackie centres a pear stone in a four-claw east–west setting, supported by a gently twisting bypass band. Soft curves wrap around the basket, creating a light, contemporary silhouette with sculptural balance. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'pear'::enum_ring_shape,
  'east_west'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-jana',
  'Jana',
  'Jana - Pear and Marquise Claw Toi et Moi with Cathedral High Setting Engagement Ring',
  'The exquisite Jana toi et moi engagement ring showcases a pear cut and marquise cut stone placed side by side atop an elegant cathedral setting. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'pear'::enum_ring_shape,
  'toi_et_moi'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-jane',
  'Jane',
  'Jane - Emerald 4 Claw Solitaire with Hidden Halo and Cathedral Setting Engagement Ring',
  'Jane is a sophisticated 4-claw emerald solitaire engagement ring with the added beauty of a hidden halo and cathedral setting. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'emerald'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-jayden',
  'Jayden',
  'Jayden - Round Claw Solitaire with Petal Gallery and Cigar Band Engagement Ring',
  'Clasped by six eagle-tipped claws in a petal design, the Jayden engagement ring displays a stunning round cut centre stone set low within a thick cigar band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-jaylene',
  'Jaylene',
  'Jaylene - Round 4 Claw Trilogy with Round Side Stones, Twisted Pave Band and Trellis Gallery Engagement Ring',
  'Jaylene is an exquisite round stone trilogy with an intricate twisted pavé band and woven trellis setting. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'trilogy'::enum_ring_setting_style,
  'pave'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-jennifer',
  'Jennifer',
  'Jennifer - Pear 5 Claw Solitaire with Bypass Band Engagement Ring',
  'Jennifer centres a pear-shaped stone in a refined five-claw setting, supported by a gently twisting bypass band. Soft curves wrap around the basket, creating a light, contemporary silhouette. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'pear'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-josephine',
  'Josephine',
  'Josephine - Radiant 4 Claw Solitaire with Round Accent Stones and Wrap Around Hidden Halo Engagement Ring',
  'The 4-claw radiant solitaire design is elevated in the Josephine ring with a unique round cut side stone band and sparkling wrap-around hidden halo. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'accents'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-journee',
  'Journee',
  'Journee - Statement Emerald Bezel Solitaire with Open Cathedral Setting Engagement Ring',
  'Simple and sophisticated, the Journee engagement ring features a striking emerald cut centre stone framed within a bezel setting. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'emerald'::enum_ring_shape,
  'bezel'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-judy',
  'Judy',
  'Judy - Radiant 4 Claw Solitaire Engagement Ring',
  'The Judy engagement ring is a timeless solitaire design featuring an exquisite radiant cut centre stone and 4-claw setting. This elegant engagement ring is available in both high and low setting heights. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'radiant'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-julia',
  'Julia',
  'Julia - Oval 4 Claw Solitaire with Hidden Halo, Pave Band and Cathedral High Setting Engagement Ring',
  'Julia is a stunning 4-claw oval solitaire featuring a sparkling hidden halo, sweeping cathedral arches and a 2/3 pavé band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'oval'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'pave'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-juliette',
  'Juliette',
  'Juliette - Radiant 4 Claw Trilogy with Trapezoid Side Stones and Low Setting Engagement Ring',
  'The graceful Juliette design showcases a radiant cut centre stone bordered by two brilliant trapezoid accent stones within a low-set basket setting. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'radiant'::enum_ring_shape,
  'trilogy'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'low_set'::enum_ring_setting_profile
),
(
  'ring-kala',
  'Kala',
  'Kala - Oval 4 Claw Solitaire with Bypass Band Engagement Ring',
  'Kala centres an oval stone in a four-claw setting, framed by a gently twisting bypass band. The band’s soft curves move around the basket, giving the design a light, contemporary silhouette with sculptural ease. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'oval'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-kate',
  'Kate',
  'Kate - Emerald 4 Claw Solitaire with Cigar Band and Hidden Halo Engagement Ring',
  'Kate showcases a sophisticated 4-claw emerald solitaire, sparkling hidden halo and thick cigar band. Kate is available in both high and low setting heights. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'emerald'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-kelsey',
  'Kelsey',
  'Kelsey - Elongated Cushion 4 Claw Solitaire with Cathedral Setting and Open Trellis Gallery Engagement Ring',
  'The timeless 4-claw elongated cushion solitaire design is elevated in the Kelsey engagement ring with a romantic woven trellis setting. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'elongated_cushion'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-kiana',
  'Kiana',
  'Kiana - Oval 4 Claw Solitaire with Hidden Halo and Floating Cathedral Low Setting Engagement Ring',
  'Kiana is a modern solitaire that doesn''t ask you to choose between beauty and practicality. Featuring a low-set oval centre stone, its open bridge and hidden halo create a graceful floating effect, allowing the design to sit low on the finger while pairing seamlessly flush with a matching wedding band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'oval'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'low_set'::enum_ring_setting_profile
),
(
  'ring-kimia',
  'Kimia',
  'Kimia - Round 4 Claw Solitaire with Bypass Band Engagement Ring',
  'Kimia centres a round stone in a refined four-claw setting, supported by a gently twisting bypass band. Soft curves wrap around the basket, creating a light, contemporary silhouette with sculptural balance. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-kirsten',
  'Kirsten',
  'Kirsten - Pear 6 Claw Solitaire with Pave Band and Halo and Low Setting Engagement Ring',
  'The Kirsten engagement ring is a glamourous 6-claw pear halo design with low-set basket setting and sparkling half pavé band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'pear'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'pave'::enum_ring_band_type,
  'low_set'::enum_ring_setting_profile
),
(
  'ring-kyla',
  'Kyla',
  'Kyla - Radiant Claw Solitaire with Marquise-Round Accent Stones and Wrap Around Hidden Halo Engagement Ring',
  'Kyla is a showstopping 4-claw radiant solitaire design with the extra sparkle of a wrap-around hidden halo and distinct pattern of round and marquise cut accent stones placed along the band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'accents'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-lara',
  'Lara',
  'Lara - Oval 4 Claw Solitaire with Hidden Halo and Twisted Alternating Pave Band Engagement Ring',
  'Lara is an elegant braided engagement ring displaying an interweaving half-circle of sleek pavé and polished metal, 4-claw oval cut centre stone and sparkling hidden halo. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'oval'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'pave'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-leila',
  'Leila',
  'Leila - Marquise 6 Claw Solitaire with Cathedral Setting Engagement Ring',
  'Leila is a classic 6-claw marquise solitaire design with beautiful cathedral arches and a polished band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'marquise'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-leslie',
  'Leslie',
  'Leslie - Round Claw Solitaire with Hidden Halo, Opposing Marquise Accents and Cathedral High Setting Engagement Ring',
  'The Leslie engagement ring showcases a 4-claw round centre stone, illuminated by a hidden halo beneath. A refined cathedral setting gives height and presence, while opposing marquise-cut side stones taper delicately along the band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'accents'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-lexie',
  'Lexie',
  'Lexie - Statement Oval Bezel Solitaire with Open Cathedral Setting Engagement Ring',
  'Lexie is a striking bezel-set oval solitaire, graced with elegant cathedral arches to accentuate the brilliance of this raised centre stone. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'oval'::enum_ring_shape,
  'bezel'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-liberty',
  'Liberty',
  'Liberty - Radiant 4 Claw Solitaire with Wrap Around Hidden Halo Engagement Ring',
  'Liberty is a stunning solitaire design featuring a radiant cut centre stone, four eagle-tipped claws and a wrap-around hidden halo. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-lilly',
  'Lilly',
  'Lilly - Round 4 Claw Solitaire Engagement Ring',
  'Lilly is a timeless classic solitaire design featuring a beautiful round cut centre stone held in a delicate high-set 4-claw setting. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-lorelai',
  'Lorelai',
  'Lorelai - Round Claw Solitaire with Hidden Halo and Twisted Alternating Pave Band Engagement Ring',
  'Lorelai is an elegant twisted engagement ring displaying an interweaving half-circle of sleek pavé and polished metal, 4-claw round cut centre stone and sparkling hidden halo. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'pave'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-lorena',
  'Lorena',
  'Lorena - Round Claw Solitaire with Bypass Band and Clustered Round-Marquise Accent Stones Engagement Ring',
  'Lorena pairs a round centre stone with a contemporary bypass setting. Curved lines are finished with round and marquise accent stones creating an open, sculptural silhouette. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'accents'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-louise',
  'Louise',
  'Louise - Round 6 Claw Solitaire Engagement Ring',
  'Louise is a classic solitaire engagement ring showcasing a stunning round cut centre stone held by six elegant eagle-tipped claws. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-luna',
  'Luna',
  'Luna - Round 4 Claw Solitaire with Hidden Halo and Floating Cathedral Low Setting Engagement Ring',
  'Luna is a modern solitaire that doesn''t ask you to choose between beauty and practicality. Featuring a low-set round centre stone, its open bridge and hidden halo create a graceful floating effect, allowing the design to sit low on the finger while pairing seamlessly flush with a matching wedding band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'low_set'::enum_ring_setting_profile
),
(
  'ring-mabeline',
  'Mabeline',
  'Mabeline - Oval 4 Claw Solitaire with East West Setting and Raised Basket Gallery Engagement Ring',
  'Mabeline is a sleek east-west design featuring a stunning oval cut centre stone placed horizontally in a low-set 4-claw basket setting. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'oval'::enum_ring_shape,
  'east_west'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-madeline',
  'Madeline',
  'Madeline - Pear 5 Claw Solitaire with Halo and Pave Band and Cathedral Setting Engagement Ring',
  'The Madeline engagement ring is an elegant pear halo design featuring five eagle-tipped claws, basket setting and 2/3 pavé band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'pear'::enum_ring_shape,
  'halo'::enum_ring_setting_style,
  'pave'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-maeve',
  'Maeve',
  'Maeve - Round Bezel Solitaire with Twisted Gallery Engagement Ring',
  'The Maeve design is a stunning round bezel-set engagement ring with cathedral arches and a striking twisted gallery. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'bezel'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-mahlia',
  'Mahlia',
  'Mahlia - Round 6 Claw Solitaire with Sweeping Micropavé Band Engagement Ring',
  'Mahlia is an exquisite round solitaire design with a sweeping micro pavé band and six delicate round claws. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'pave'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-maisy',
  'Maisy',
  'Maisy - Round 6 Claw Solitaire with Pave Band and Cathedral Setting Engagement Ring',
  'Maisy is a sophisticated 6-claw round solitaire design featuring a sweeping cathedral setting and sparkling 2/3 pavé band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'pave'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-mariah',
  'Mariah',
  'Mariah - Round 6 Claw Solitaire with Crown Gallery Engagement Ring',
  'Mariah is an elegant low-set solitaire design with a round cut centre stone and six eagle-tipped claws. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'round'::enum_ring_shape,
  'solitaire'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-matisse',
  'Matisse',
  'Matisse - Emerald 4 Claw Solitaire with Bezel Frame Engagement Ring',
  'Designed to be worn low set, the Matisse is an emerald cut solitaire that blends vintage character with sculptural modern design for an effortlessly elevated silhouette that features a subtle under bezel frame and our signature eagle claws, offering the perfect balance for those torn between a bezel and a claw setting. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'emerald'::enum_ring_shape,
  'bezel'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-meghan',
  'Meghan',
  'Meghan - Elongated Cushion 8 Double Claw Trilogy with Round Side Stones, Pave Band and Cathedral Setting Engagement Ring',
  'The Meghan engagement ring is an exact replica of the iconic engagement ring worn by Meghan Markle, featuring an elongated cushion cut centre stone neighboured by two round cut side stones and a 2/3 pavé band. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'elongated_cushion'::enum_ring_shape,
  'trilogy'::enum_ring_setting_style,
  'pave'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
),
(
  'ring-meesha',
  'Meesha',
  'Meesha - Oval Bezel Solitaire with Marquise-Round Shoulder Stones and Cathedral Setting Engagement Ring',
  'The Meesha design showcases a striking bezel-set oval cut centre stone accented by round and marquise cut stones. Schedule an appointment with Cullen US today.',
  1500,
  'USD',
  'oval'::enum_ring_shape,
  'bezel'::enum_ring_setting_style,
  'plain'::enum_ring_band_type,
  'high_set'::enum_ring_setting_profile
)
ON CONFLICT (slug) DO NOTHING;
